(* Code automatically generated by 'PreSARAH' *) 
(* Expressions for amplitudes are obtained by FeynArts/FormCalc *) 
(* This file is supposed to be loaded and used by SARAH *) 
(* Created at 4:14 on 7.1.2021 *) 
 
 
PrintDebug["   ... ",TreeVYphill]; 
NamesParticles =  {ChargedLepton, bar[ChargedLepton], DownQuark, bar[DownQuark]}; 
 NamesOperators =  {TVOYphillVRR, TVOYphillVLL, TVOYphillVRL, TVOYphillVLR, TVOYphillTLL, TVOYphillTLR, TVOYphillTRL, TVOYphillTRR}; 
 NeglectInsertionOrderTree[TreeVYphill] =  {}; 
NeglectCrossedDiagrams[TreeVYphill] = False; 
NameProcess = TreeVYphill; 
 
Generate[TreeVYphill][file_]:=Block[{i,j,k}, 
 

 (* Creating all possible processes; extract information about involved masses/couplings *) 


(* ------------------------------- *)
(* {ChargedLepton, bar[ChargedLepton], DownQuark, bar[DownQuark]} *)
(* ------------------------------- *)
 
GetInformtion4FermionProcess[ChargedLepton,bar[ChargedLepton],DownQuark,bar[DownQuark],TreeVYphill,file]; 
NeededMassesAll=Intersection[NeededMasses];
NeededCouplingsAll=Intersection[NeededCouplings];
WriteCodeObservablePreSARAH[TreeVYphill][NeededMassesAll,NeededCouplingsAll,TreeContributionsScalar,TreeContributionsVector,WaveContributionsScalar,WaveContributionsVector,WaveContributionsPhoton,PenguinContributionsScalar,PenguinContributionsVector,PenguinContributionsPhoton,BoxContributions,file]; 
NeededMassAllSaved[TreeVYphill] = masses 
]; 

WriteCodeObservablePreSARAH[TreeVYphill][masses_,couplings_,treeScalar_,treeVector_,waveScalar_,waveVector_,wavePhoton_,penguinScalar_,penguinVector_,penguinPhoton_,box_,file_] :=Block[{i,j,k,fermions,scalars}, 
 
NeededMassesAllSaved[TreeVYphill] = masses; 
NeededCouplingsAllSaved[TreeVYphill] = couplings; 
NeededCombinations[TreeVYphill] = {{2, 1, 2, 2}, {3, 1, 2, 2}, {3, 2, 2, 2}, {2, 1, 3, 3}, {3, 1, 3, 3}, {3, 2, 3, 3}}; 
PrintDebug["     writing SPheno code for ",TreeVYphill]; 
MakeSubroutineTitle["CalculateTreeVYphill",Flatten[{masses,couplings}],{"gt1","gt2","gt3","gt4","OnlySM"}, 
{"TVOYphillVRR", "TVOYphillVLL", "TVOYphillVRL", "TVOYphillVLR", "TVOYphillTLL", "TVOYphillTLR", "TVOYphillTRL", "TVOYphillTRR"},file]; 
WriteString[file,"! ---------------------------------------------------------------- \n"]; 
WriteString[file,"! Code based on automatically generated SARAH extensions by 'PreSARAH' \n"]; 
WriteString[file,"! Expressions for amplitudes are obtained by FeynArts/FormCalc \n"]; 
WriteString[file,"! Based on user input for process TreeVYphill \n"]; 
WriteString[file,"! 'PreSARAH' output has been generated  at 4:14 on 7.1.2021 \n"]; 
WriteString[file,"! ---------------------------------------------------------------- \n \n"]; 
 
 
WriteString[file,"Implicit None \n"]; 
MakeVariableList[Flatten[{couplings,masses}],",Intent(in)",file];
WriteString[file,"Integer,Intent(in) :: gt1, gt2,gt3,gt4 \n"];
WriteString[file,"Logical, Intent(in) :: OnlySM \n"];
WriteString[file,"Integer :: iprop, i1, i2, i3, i4 \n"];
WriteString[file,"Real(dp) :: MassEx1,MassEx2,MassEx3,MassEx4, MassEx12,MassEx22,MassEx32,MassEx42 \n"];
WriteString[file,"Complex(dp), Intent(out) :: TVOYphillVRR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVOYphillVLL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVOYphillVRL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVOYphillVLR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVOYphillTLL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVOYphillTLR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVOYphillTRL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVOYphillTRR \n"]; 
WriteString[file,"Complex(dp) :: vertex1L, vertex1R, vertex2L, vertex2R \n"];
WriteString[file,"Real(dp) ::  MP, MP2, IMP2, IMP, MFin, MFin2, IMFin, IMFin2, Finite  \n"];
WriteString[file,"Real(dp) ::  MS1, MS12, MS2, MS22, MF1, MF12, MF2, MF22, MV1, MV12, MV2, MV22  \n"];
WriteString[file,"Complex(dp) ::  chargefactor  \n"];
WriteString[file,"Complex(dp) ::  coup1L, coup1R, coup2L, coup2R, coup3L, coup3R, coup3, coup4L, coup4R \n\n"];

WriteString[file,"Complex(dp) ::  int1,int2,int3,int4,int5,int6,int7,int8 \n\n"];

WriteString[file,"Iname=Iname+1 \n"];
WriteString[file,"NameOfUnit(Iname)='CalculateTreeVYphill' \n
"];
 
AddCalcSquaredMasses[masses,file]; 
(* Initaliziation *)
WriteString[file,"Finite=1._dp \n"];
WriteString[file,"MassEx1="<>SPhenoMass[ChargedLepton,gt1]<>"  \n"];
WriteString[file,"MassEx12="<>SPhenoMassSq[ChargedLepton,gt1]<>" \n"];
WriteString[file,"MassEx2="<>SPhenoMass[bar[ChargedLepton],gt2]<>"  \n"];
WriteString[file,"MassEx22="<>SPhenoMassSq[bar[ChargedLepton],gt2]<>" \n"];
WriteString[file,"MassEx3="<>SPhenoMass[DownQuark,gt3]<>"  \n"];
WriteString[file,"MassEx32="<>SPhenoMassSq[DownQuark,gt3]<>" \n"];
WriteString[file,"MassEx4="<>SPhenoMass[bar[DownQuark],gt4]<>"  \n"];
WriteString[file,"MassEx42="<>SPhenoMassSq[bar[DownQuark],gt4]<>" \n"];
WriteString[file,"! ------------------------------ \n "];
WriteString[file,"! Amplitudes for external states \n "];
WriteString[file,"! {ChargedLepton, bar[ChargedLepton], DownQuark, bar[DownQuark]} \n "];
WriteString[file,"! ------------------------------ \n \n"];
WriteString[sphenoTeX,"\\section{External states: $"<>TeXOutput[{ChargedLepton[{gt1}], bar[ChargedLepton][{gt2}], DownQuark[{gt3}], bar[DownQuark][{gt4}]}]<>"$} \n"];
WriteString[file,"TVOYphillVRR=0._dp \n"]; 
WriteString[file,"TVOYphillVLL=0._dp \n"]; 
WriteString[file,"TVOYphillVRL=0._dp \n"]; 
WriteString[file,"TVOYphillVLR=0._dp \n"]; 
WriteString[file,"TVOYphillTLL=0._dp \n"]; 
WriteString[file,"TVOYphillTLR=0._dp \n"]; 
WriteString[file,"TVOYphillTRL=0._dp \n"]; 
WriteString[file,"TVOYphillTRR=0._dp \n"]; 
WriteDiagramsObservable[TreeVYphill,{}, treeVector, {},  {}, {}, {}, {}, file];
WriteString[file,"Iname=Iname-1\n\n"]; 
WriteString[file,"End Subroutine CalculateTreeVYphill \n\n"]; 
]; 
AddTreeResultPreSARAH[TreeVYphill][prop_,top_,type_,file_]:=Block[{}, 

 (* This routine returns the generic expression for the amplitude of a given triangle diagram *) 
 
Switch[prop,
V, (* Vector penguins *) 
 Switch[top,  (* Check topology *) 
  1, 
	 	 WriteStringFLB[file,"  TVOYphillVRR=TVOYphillVRR+ -1.*coup1R*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillVRR= & "<> StringReplace["-(coup1R coup2R IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillVLL=TVOYphillVLL+ -1.*coup1L*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillVLL= & "<> StringReplace["-(coup1L coup2L IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillVRL=TVOYphillVRL+ -1.*coup1R*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillVRL= & "<> StringReplace["-(coup1R coup2L IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillVLR=TVOYphillVLR+ -1.*coup1L*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillVLR= & "<> StringReplace["-(coup1L coup2R IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillTLL=TVOYphillTLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillTLR=TVOYphillTLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillTRL=TVOYphillTRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillTRR=TVOYphillTRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
,
  2, 
	 	 WriteStringFLB[file,"  TVOYphillVRR=TVOYphillVRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillVRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillVLL=TVOYphillVLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillVLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillVRL=TVOYphillVRL+ -1.*coup1L*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillVRL= & "<> StringReplace["-(coup1L coup2R IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillVLR=TVOYphillVLR+ -1.*coup1R*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillVLR= & "<> StringReplace["-(coup1R coup2L IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillTLL=TVOYphillTLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillTLR=TVOYphillTLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillTRL=TVOYphillTRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillTRR=TVOYphillTRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
,
  3, 
	 	 WriteStringFLB[file,"  TVOYphillVRR=TVOYphillVRR+ -1.*coup1R*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillVRR= & "<> StringReplace["-(coup1R coup2R IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillVLL=TVOYphillVLL+ -1.*coup1L*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillVLL= & "<> StringReplace["-(coup1L coup2L IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillVRL=TVOYphillVRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillVRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillVLR=TVOYphillVLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillVLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillTLL=TVOYphillTLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillTLR=TVOYphillTLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillTRL=TVOYphillTRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOYphillTRR=TVOYphillTRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
];,
S, (* Scalar penguins *) 
Return[]; (* not necessary *) ]; 
]; 


