(* Code automatically generated by 'PreSARAH' *) 
(* Expressions for amplitudes are obtained by FeynArts/FormCalc *) 
(* This file is supposed to be loaded and used by SARAH *) 
(* Created at 4:13 on 7.1.2021 *) 
 
 
PrintDebug["   ... ",BoxYphill]; 
NamesParticles =  {ChargedLepton, bar[ChargedLepton], DownQuark, bar[DownQuark]}; 
 NamesOperators =  {BOYphillVRR, BOYphillVLL, BOYphillVRL, BOYphillVLR, BOYphillTLL, BOYphillTLR, BOYphillTRL, BOYphillTRR}; 
 NeglectInsertionOrderBox[BoxYphill] = {}; 
NeglectCrossedDiagrams[BoxYphill] = False; 
NameProcess = BoxYphill; 
 
Generate[BoxYphill][file_]:=Block[{i,j,k}, 
 

 (* Creating all possible processes; extract information about involved masses/couplings *) 


(* ------------------------------- *)
(* {ChargedLepton, bar[ChargedLepton], DownQuark, bar[DownQuark]} *)
(* ------------------------------- *)
 
GetInformtion4FermionProcess[ChargedLepton,bar[ChargedLepton],DownQuark,bar[DownQuark],BoxYphill,file]; 
NeededMassesAll=Intersection[NeededMasses];
NeededCouplingsAll=Intersection[NeededCouplings];
WriteCodeObservablePreSARAH[BoxYphill][NeededMassesAll,NeededCouplingsAll,TreeContributionsScalar,TreeContributionsVector,WaveContributionsScalar,WaveContributionsVector,WaveContributionsPhoton,PenguinContributionsScalar,PenguinContributionsVector,PenguinContributionsPhoton,BoxContributions,file]; 
NeededMassAllSaved[BoxYphill] = masses 
]; 

WriteCodeObservablePreSARAH[BoxYphill][masses_,couplings_,treeScalar_,treeVector_,waveScalar_,waveVector_,wavePhoton_,penguinScalar_,penguinVector_,penguinPhoton_,box_,file_] :=Block[{i,j,k,fermions,scalars}, 
 
NeededMassesAllSaved[BoxYphill] = masses; 
NeededCouplingsAllSaved[BoxYphill] = couplings; 
NeededCombinations[BoxYphill] = {{2, 1, 2, 2}, {3, 1, 2, 2}, {3, 2, 2, 2}, {2, 1, 3, 3}, {3, 1, 3, 3}, {3, 2, 3, 3}}; 
PrintDebug["     writing SPheno code for ",BoxYphill]; 
MakeSubroutineTitle["CalculateBoxYphill",Flatten[{masses,couplings}],{"gt1","gt2","gt3","gt4","OnlySM"}, 
{"BOYphillVRR", "BOYphillVLL", "BOYphillVRL", "BOYphillVLR", "BOYphillTLL", "BOYphillTLR", "BOYphillTRL", "BOYphillTRR"},file]; 
WriteString[file,"! ---------------------------------------------------------------- \n"]; 
WriteString[file,"! Code based on automatically generated SARAH extensions by 'PreSARAH' \n"]; 
WriteString[file,"! Expressions for amplitudes are obtained by FeynArts/FormCalc \n"]; 
WriteString[file,"! Based on user input for process BoxYphill \n"]; 
WriteString[file,"! 'PreSARAH' output has been generated  at 4:13 on 7.1.2021 \n"]; 
WriteString[file,"! ---------------------------------------------------------------- \n \n"]; 
 
 
WriteString[file,"Implicit None \n"]; 
MakeVariableList[Flatten[{couplings,masses}],",Intent(in)",file];
WriteString[file,"Integer,Intent(in) :: gt1, gt2,gt3,gt4 \n"];
WriteString[file,"Logical, Intent(in) :: OnlySM \n"];
WriteString[file,"Integer :: iprop, i1, i2, i3, i4 \n"];
WriteString[file,"Real(dp) :: MassEx1,MassEx2,MassEx3,MassEx4, MassEx12,MassEx22,MassEx32,MassEx42 \n"];
WriteString[file,"Complex(dp), Intent(out) :: BOYphillVRR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: BOYphillVLL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: BOYphillVRL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: BOYphillVLR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: BOYphillTLL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: BOYphillTLR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: BOYphillTRL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: BOYphillTRR \n"]; 
WriteString[file,"Complex(dp) :: vertex1L, vertex1R, vertex2L, vertex2R \n"];
WriteString[file,"Real(dp) ::  MP, MP2, IMP2, IMP, MFin, MFin2, IMFin, IMFin2, Finite  \n"];
WriteString[file,"Real(dp) ::  MS1, MS12, MS2, MS22, MF1, MF12, MF2, MF22, MV1, MV12, MV2, MV22  \n"];
WriteString[file,"Complex(dp) ::  chargefactor  \n"];
WriteString[file,"Complex(dp) ::  coup1L, coup1R, coup2L, coup2R, coup3L, coup3R, coup3, coup4L, coup4R \n\n"];

WriteString[file,"Complex(dp) ::  int1,int2,int3,int4,int5,int6,int7,int8 \n\n"];

WriteString[file,"Iname=Iname+1 \n"];
WriteString[file,"NameOfUnit(Iname)='CalculateBoxYphill' \n
"];
 
AddCalcSquaredMasses[masses,file]; 
(* Initaliziation *)
WriteString[file,"Finite=1._dp \n"];
WriteString[file,"MassEx1="<>SPhenoMass[ChargedLepton,gt1]<>"  \n"];
WriteString[file,"MassEx12="<>SPhenoMassSq[ChargedLepton,gt1]<>" \n"];
WriteString[file,"MassEx2="<>SPhenoMass[bar[ChargedLepton],gt2]<>"  \n"];
WriteString[file,"MassEx22="<>SPhenoMassSq[bar[ChargedLepton],gt2]<>" \n"];
WriteString[file,"MassEx3="<>SPhenoMass[DownQuark,gt3]<>"  \n"];
WriteString[file,"MassEx32="<>SPhenoMassSq[DownQuark,gt3]<>" \n"];
WriteString[file,"MassEx4="<>SPhenoMass[bar[DownQuark],gt4]<>"  \n"];
WriteString[file,"MassEx42="<>SPhenoMassSq[bar[DownQuark],gt4]<>" \n"];
WriteString[file,"! ------------------------------ \n "];
WriteString[file,"! Amplitudes for external states \n "];
WriteString[file,"! {ChargedLepton, bar[ChargedLepton], DownQuark, bar[DownQuark]} \n "];
WriteString[file,"! ------------------------------ \n \n"];
WriteString[sphenoTeX,"\\section{External states: $"<>TeXOutput[{ChargedLepton[{gt1}], bar[ChargedLepton][{gt2}], DownQuark[{gt3}], bar[DownQuark][{gt4}]}]<>"$} \n"];
WriteString[file,"BOYphillVRR=0._dp \n"]; 
WriteString[file,"BOYphillVLL=0._dp \n"]; 
WriteString[file,"BOYphillVRL=0._dp \n"]; 
WriteString[file,"BOYphillVLR=0._dp \n"]; 
WriteString[file,"BOYphillTLL=0._dp \n"]; 
WriteString[file,"BOYphillTLR=0._dp \n"]; 
WriteString[file,"BOYphillTRL=0._dp \n"]; 
WriteString[file,"BOYphillTRR=0._dp \n"]; 
WriteDiagramsObservable[BoxYphill,{}, {}, {}, {}, {}, {}, box, file];
WriteString[file,"BOYphillVRR=oo16pi2*BOYphillVRR \n"]; 
WriteString[file,"BOYphillVLL=oo16pi2*BOYphillVLL \n"]; 
WriteString[file,"BOYphillVRL=oo16pi2*BOYphillVRL \n"]; 
WriteString[file,"BOYphillVLR=oo16pi2*BOYphillVLR \n"]; 
WriteString[file,"BOYphillTLL=oo16pi2*BOYphillTLL \n"]; 
WriteString[file,"BOYphillTLR=oo16pi2*BOYphillTLR \n"]; 
WriteString[file,"BOYphillTRL=oo16pi2*BOYphillTRL \n"]; 
WriteString[file,"BOYphillTRR=oo16pi2*BOYphillTRR \n"]; 
WriteString[file,"Iname=Iname-1\n\n"]; 
WriteString[file,"End Subroutine CalculateBoxYphill \n\n"]; 
]; 
AddBoxResultPreSARAH[BoxYphill][top_,type_,file_]:=Block[{}, 

 (* This routine returns the generic expression for the amplitude of a given box diagram *) 
 
Switch[top, (* check in which order the external legs are glued to the box *) 
1, 
   Switch[type, (* Check the generic type of the diagram *) 
	FSSF, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mS22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mS22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+-1.*chargefactor*coup1R*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["-(chargefactor coup1R coup2L coup3R coup4L I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+-1.*chargefactor*coup1L*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["-(chargefactor coup1L coup2R coup3L coup4R I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+-1.*chargefactor*coup1R*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["-(chargefactor coup1R coup2L coup3L coup4R I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+-1.*chargefactor*coup1L*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["-(chargefactor coup1L coup2R coup3R coup4L I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	SFFS, 
	 	 WriteString[file,"  int1=D00check(mF22, mF12, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF22, mF12, mS12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF22, mF12, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mS12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+-1.*chargefactor*coup1R*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["-(chargefactor coup1R coup2L coup3R coup4L I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+-1.*chargefactor*coup1L*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["-(chargefactor coup1L coup2R coup3L coup4R I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+0.5*chargefactor*coup1R*coup2L*coup3L*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["(chargefactor coup1R coup2L coup3L coup4R I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+0.5*chargefactor*coup1L*coup2R*coup3R*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["(chargefactor coup1L coup2R coup3R coup4L I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	FSVF, 
	 	 WriteString[file,"  int1=MMD0(mF1, mF2, mF12, mF22, mV22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mV22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+chargefactor*coup1R*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["chargefactor coup1R coup2R coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+chargefactor*coup1L*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["chargefactor coup1L coup2L coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+chargefactor*coup1R*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["chargefactor coup1R coup2R coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+chargefactor*coup1L*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["chargefactor coup1L coup2L coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	FVSF, 
	 	 WriteString[file,"  int1=MMD0(mF1, mF2, mF12, mF22, mS22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mS22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+chargefactor*coup1R*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+chargefactor*coup1L*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+chargefactor*coup1R*coup2L*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["chargefactor coup1R coup2L coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+chargefactor*coup1L*coup2R*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["chargefactor coup1L coup2R coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	SFFV, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mF12, mV22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mF12, mV22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=D00check(mF22, mF12, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["D_{27}(mF22, mF12, mS12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int3=MMD0(mF1, mF2, mF22, mF12, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_3 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mS12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+chargefactor*coup1R*coup2L*coup3R*coup4R*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4R I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+chargefactor*coup1L*coup2R*coup3L*coup4L*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4L I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+-1.*chargefactor*coup1R*coup2L*coup3L*coup4L*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["-(chargefactor coup1R coup2L coup3L coup4L (I_1 - 2 I_2))",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+-1.*chargefactor*coup1L*coup2R*coup3R*coup4R*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["-(chargefactor coup1L coup2R coup3R coup4R (I_1 - 2 I_2))",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	VFFS, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mF12, mS22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mF12, mS22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=D00check(mF22, mF12, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["D_{27}(mF22, mF12, mV12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int3=MMD0(mF1, mF2, mF22, mF12, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_3 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mV12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+chargefactor*coup1R*coup2R*coup3R*coup4L*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["chargefactor coup1R coup2R coup3R coup4L I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+chargefactor*coup1L*coup2L*coup3L*coup4R*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["chargefactor coup1L coup2L coup3L coup4R I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+-1.*chargefactor*coup1R*coup2R*coup3L*coup4R*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["-(chargefactor coup1R coup2R coup3L coup4R (I_1 - 2 I_2))",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+-1.*chargefactor*coup1L*coup2L*coup3R*coup4L*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["-(chargefactor coup1L coup2L coup3R coup4L (I_1 - 2 I_2))",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	FVVF, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mV22, mV12, mF12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mV22, mV12, mF12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=D00check(mF12, mF22, mV22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["D_{27}(mF12, mF22, mV22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+-4.*chargefactor*coup1R*coup2R*coup3R*coup4R*(int1 - 3.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["-4 chargefactor coup1R coup2R coup3R coup4R (I_1 - 3 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+-4.*chargefactor*coup1L*coup2L*coup3L*coup4L*(int1 - 3.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["-4 chargefactor coup1L coup2L coup3L coup4L (I_1 - 3 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+-4.*chargefactor*coup1R*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["-4 chargefactor coup1R coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+-4.*chargefactor*coup1L*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["-4 chargefactor coup1L coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	VFFV, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mF12, mV22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mF12, mV22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=D00check(mF22, mF12, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["D_{27}(mF22, mF12, mV12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int3=MMD0(mF1, mF2, mF22, mF12, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_3 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mV12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+-4.*chargefactor*coup1R*coup2R*coup3R*coup4R*(int1 - 3.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["-4 chargefactor coup1R coup2R coup3R coup4R (I_1 - 3 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+-4.*chargefactor*coup1L*coup2L*coup3L*coup4L*(int1 - 3.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["-4 chargefactor coup1L coup2L coup3L coup4L (I_1 - 3 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+2.*chargefactor*coup1R*coup2R*coup3L*coup4L*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["2 chargefactor coup1R coup2R coup3L coup4L I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+2.*chargefactor*coup1L*coup2L*coup3R*coup4R*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["2 chargefactor coup1L coup2L coup3R coup4R I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
];,
2, 
   Switch[type, (* Check the generic type of the diagram *) 
	FSSF, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mS22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mS22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+chargefactor*coup1R*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+chargefactor*coup1L*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+chargefactor*coup1R*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+chargefactor*coup1L*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	SFFS, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mS12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF12, mF22, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mS12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+-0.5*chargefactor*coup1R*coup2L*coup3L*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["-(chargefactor coup1R coup2L coup3L coup4R I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+-0.5*chargefactor*coup1L*coup2R*coup3R*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["-(chargefactor coup1L coup2R coup3R coup4L I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+chargefactor*coup1R*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+chargefactor*coup1L*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	FSVF, 
	 	 WriteString[file,"  int1=MMD0(mF1, mF2, mF12, mF22, mV22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mV22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+chargefactor*coup1R*coup2R*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["chargefactor coup1R coup2R coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+chargefactor*coup1L*coup2L*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["chargefactor coup1L coup2L coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+chargefactor*coup1R*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["chargefactor coup1R coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+chargefactor*coup1L*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["chargefactor coup1L coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	FVSF, 
	 	 WriteString[file,"  int1=MMD0(mF1, mF2, mF12, mF22, mS22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mS22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+chargefactor*coup1R*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+chargefactor*coup1L*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+chargefactor*coup1R*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+chargefactor*coup1L*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	SFFV, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mS12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF12, mF22, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mS12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+2.*chargefactor*coup1R*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["2 chargefactor coup1R coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+2.*chargefactor*coup1L*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["2 chargefactor coup1L coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+-1.*chargefactor*coup1R*coup2L*coup3L*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["-(chargefactor coup1R coup2L coup3L coup4L I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+-1.*chargefactor*coup1L*coup2R*coup3R*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["-(chargefactor coup1L coup2R coup3R coup4R I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	VFFS, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mV12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF12, mF22, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mV12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+2.*chargefactor*coup1R*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["2 chargefactor coup1R coup2R coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+2.*chargefactor*coup1L*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["2 chargefactor coup1L coup2L coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+-1.*chargefactor*coup1R*coup2R*coup3R*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["-(chargefactor coup1R coup2R coup3R coup4L I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+-1.*chargefactor*coup1L*coup2L*coup3L*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["-(chargefactor coup1L coup2L coup3L coup4R I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	FVVF, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mV22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mV22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+16.*chargefactor*coup1R*coup2R*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["16 chargefactor coup1R coup2R coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+16.*chargefactor*coup1L*coup2L*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["16 chargefactor coup1L coup2L coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+4.*chargefactor*coup1R*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["4 chargefactor coup1R coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+4.*chargefactor*coup1L*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["4 chargefactor coup1L coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	VFFV, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mV12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF12, mF22, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mV12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+-2.*chargefactor*coup1R*coup2R*coup3R*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["-2 chargefactor coup1R coup2R coup3R coup4R I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+-2.*chargefactor*coup1L*coup2L*coup3L*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["-2 chargefactor coup1L coup2L coup3L coup4L I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+4.*chargefactor*coup1R*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["4 chargefactor coup1R coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+4.*chargefactor*coup1L*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["4 chargefactor coup1L coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
];,
3, 
   Switch[type, (* Check the generic type of the diagram *) 
	FSSF, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mS22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mS22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF12, mF22, mS22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mS22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+-0.5*chargefactor*coup1R*coup2L*coup3R*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["-(chargefactor coup1R coup2L coup3R coup4L I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+-0.5*chargefactor*coup1L*coup2R*coup3L*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["-(chargefactor coup1L coup2R coup3L coup4R I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+-1.*chargefactor*coup1R*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["-(chargefactor coup1R coup2R coup3L coup4L I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+-1.*chargefactor*coup1L*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["-(chargefactor coup1L coup2L coup3R coup4R I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	SFFS, 
	 	 WriteString[file,"  int1=D00check(mF22, mF12, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF22, mF12, mS12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF22, mF12, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mS12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+chargefactor*coup1R*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+chargefactor*coup1L*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+0.5*chargefactor*coup1R*coup2R*coup3L*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["(chargefactor coup1R coup2R coup3L coup4L I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+0.5*chargefactor*coup1L*coup2L*coup3R*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["(chargefactor coup1L coup2L coup3R coup4R I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	FSVF, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mV22, mS12, mF12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mV22, mS12, mF12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=D00check(mF12, mF22, mV22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["D_{27}(mF12, mF22, mV22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int3=MMD0(mF1, mF2, mF12, mF22, mV22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_3 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mV22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+chargefactor*coup1R*coup2L*coup3R*coup4R*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4R (I_1 - 2 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+chargefactor*coup1L*coup2R*coup3L*coup4L*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4L (I_1 - 2 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+chargefactor*coup1R*coup2R*coup3L*coup4R*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["chargefactor coup1R coup2R coup3L coup4R I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+chargefactor*coup1L*coup2L*coup3R*coup4L*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["chargefactor coup1L coup2L coup3R coup4L I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	FVSF, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mS22, mV12, mF12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mS22, mV12, mF12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=D00check(mF12, mF22, mS22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["D_{27}(mF12, mF22, mS22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int3=MMD0(mF1, mF2, mF12, mF22, mS22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_3 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mS22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+chargefactor*coup1R*coup2R*coup3R*coup4L*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["chargefactor coup1R coup2R coup3R coup4L (I_1 - 2 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+chargefactor*coup1L*coup2L*coup3L*coup4R*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["chargefactor coup1L coup2L coup3L coup4R (I_1 - 2 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+chargefactor*coup1R*coup2L*coup3L*coup4L*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["chargefactor coup1R coup2L coup3L coup4L I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+chargefactor*coup1L*coup2R*coup3R*coup4R*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["chargefactor coup1L coup2R coup3R coup4R I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	SFFV, 
	 	 WriteString[file,"  int1=D00check(mF22, mF12, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF22, mF12, mS12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF22, mF12, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mS12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+chargefactor*coup1R*coup2R*coup3R*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["chargefactor coup1R coup2R coup3R coup4R I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+chargefactor*coup1L*coup2L*coup3L*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["chargefactor coup1L coup2L coup3L coup4L I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+2.*chargefactor*coup1R*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["2 chargefactor coup1R coup2L coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+2.*chargefactor*coup1L*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["2 chargefactor coup1L coup2R coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	VFFS, 
	 	 WriteString[file,"  int1=D00check(mF22, mF12, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF22, mF12, mV12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF22, mF12, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mV12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+chargefactor*coup1R*coup2L*coup3R*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4L I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+chargefactor*coup1L*coup2R*coup3L*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4R I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+2.*chargefactor*coup1R*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["2 chargefactor coup1R coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+2.*chargefactor*coup1L*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["2 chargefactor coup1L coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	FVVF, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mV22, mV12, mF12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mV22, mV12, mF12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF12, mF22, mV22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mV22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+-2.*chargefactor*coup1R*coup2R*coup3R*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["-2 chargefactor coup1R coup2R coup3R coup4R I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+-2.*chargefactor*coup1L*coup2L*coup3L*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["-2 chargefactor coup1L coup2L coup3L coup4L I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+-4.*chargefactor*coup1R*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["-4 chargefactor coup1R coup2L coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+-4.*chargefactor*coup1L*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["-4 chargefactor coup1L coup2R coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	VFFV, 
	 	 WriteString[file,"  int1=D00check(mF22, mF12, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF22, mF12, mV12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF22, mF12, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mV12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOYphillVRR=BOYphillVRR+16.*chargefactor*coup1R*coup2R*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRR= & "<> StringReplace["16 chargefactor coup1R coup2R coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLL=BOYphillVLL+16.*chargefactor*coup1L*coup2L*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLL= & "<> StringReplace["16 chargefactor coup1L coup2L coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVRL=BOYphillVRL+2.*chargefactor*coup1R*coup2L*coup3L*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVRL= & "<> StringReplace["2 chargefactor coup1R coup2L coup3L coup4R I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillVLR=BOYphillVLR+2.*chargefactor*coup1L*coup2R*coup3R*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillVLR= & "<> StringReplace["2 chargefactor coup1L coup2R coup3R coup4L I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLL=BOYphillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTLR=BOYphillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRL=BOYphillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOYphillTRR=BOYphillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
];]; 
]; 


