(* Code automatically generated by 'PreSARAH' *) 
(* Created at 4:12 on 7.1.2021 *) 
 
 
ProcessWrapper = True; 
NameProcess = "Yphill" 
ExternalFields = {ChargedLepton, bar[ChargedLepton], DownQuark, bar[DownQuark]}; 
SumContributionsOperators["Yphill"] = { 
{OYphillVRR, BOYphillVRR + PSOYphillVRR + PVOYphillVRR + TSOYphillVRR + TVOYphillVRR}, 
{OYphillVLL, BOYphillVLL + PSOYphillVLL + PVOYphillVLL + TSOYphillVLL + TVOYphillVLL}, 
{OYphillVRL, BOYphillVRL + PSOYphillVRL + PVOYphillVRL + TSOYphillVRL + TVOYphillVRL}, 
{OYphillVLR, BOYphillVLR + PSOYphillVLR + PVOYphillVLR + TSOYphillVLR + TVOYphillVLR}, 
{OYphillTLL, BOYphillTLL + PSOYphillTLL + PVOYphillTLL + TSOYphillTLL + TVOYphillTLL}, 
{OYphillTLR, BOYphillTLR + PSOYphillTLR + PVOYphillTLR + TSOYphillTLR + TVOYphillTLR}, 
{OYphillTRL, BOYphillTRL + PSOYphillTRL + PVOYphillTRL + TSOYphillTRL + TVOYphillTRL}, 
{OYphillTRR, BOYphillTRR + PSOYphillTRR + PVOYphillTRR + TSOYphillTRR + TVOYphillTRR}}; 

