(* Code automatically generated by 'PreSARAH' *) 
(* Expressions for amplitudes are obtained by FeynArts/FormCalc *) 
(* This file is supposed to be loaded and used by SARAH *) 
(* Created at 4:14 on 7.1.2021 *) 
 
 
PrintDebug["   ... ",TreeSYphill]; 
NamesParticles =  {ChargedLepton, bar[ChargedLepton], DownQuark, bar[DownQuark]}; 
 NamesOperators =  {TSOYphillVRR, TSOYphillVLL, TSOYphillVRL, TSOYphillVLR, TSOYphillTLL, TSOYphillTLR, TSOYphillTRL, TSOYphillTRR}; 
 NeglectInsertionOrderTree[TreeSYphill] =  {}; 
NeglectCrossedDiagrams[TreeSYphill] = False; 
NameProcess = TreeSYphill; 
 
Generate[TreeSYphill][file_]:=Block[{i,j,k}, 
 

 (* Creating all possible processes; extract information about involved masses/couplings *) 


(* ------------------------------- *)
(* {ChargedLepton, bar[ChargedLepton], DownQuark, bar[DownQuark]} *)
(* ------------------------------- *)
 
GetInformtion4FermionProcess[ChargedLepton,bar[ChargedLepton],DownQuark,bar[DownQuark],TreeSYphill,file]; 
NeededMassesAll=Intersection[NeededMasses];
NeededCouplingsAll=Intersection[NeededCouplings];
WriteCodeObservablePreSARAH[TreeSYphill][NeededMassesAll,NeededCouplingsAll,TreeContributionsScalar,TreeContributionsVector,WaveContributionsScalar,WaveContributionsVector,WaveContributionsPhoton,PenguinContributionsScalar,PenguinContributionsVector,PenguinContributionsPhoton,BoxContributions,file]; 
NeededMassAllSaved[TreeSYphill] = masses 
]; 

WriteCodeObservablePreSARAH[TreeSYphill][masses_,couplings_,treeScalar_,treeVector_,waveScalar_,waveVector_,wavePhoton_,penguinScalar_,penguinVector_,penguinPhoton_,box_,file_] :=Block[{i,j,k,fermions,scalars}, 
 
NeededMassesAllSaved[TreeSYphill] = masses; 
NeededCouplingsAllSaved[TreeSYphill] = couplings; 
NeededCombinations[TreeSYphill] = {{2, 1, 2, 2}, {3, 1, 2, 2}, {3, 2, 2, 2}, {2, 1, 3, 3}, {3, 1, 3, 3}, {3, 2, 3, 3}}; 
PrintDebug["     writing SPheno code for ",TreeSYphill]; 
MakeSubroutineTitle["CalculateTreeSYphill",Flatten[{masses,couplings}],{"gt1","gt2","gt3","gt4","OnlySM"}, 
{"TSOYphillVRR", "TSOYphillVLL", "TSOYphillVRL", "TSOYphillVLR", "TSOYphillTLL", "TSOYphillTLR", "TSOYphillTRL", "TSOYphillTRR"},file]; 
WriteString[file,"! ---------------------------------------------------------------- \n"]; 
WriteString[file,"! Code based on automatically generated SARAH extensions by 'PreSARAH' \n"]; 
WriteString[file,"! Expressions for amplitudes are obtained by FeynArts/FormCalc \n"]; 
WriteString[file,"! Based on user input for process TreeSYphill \n"]; 
WriteString[file,"! 'PreSARAH' output has been generated  at 4:14 on 7.1.2021 \n"]; 
WriteString[file,"! ---------------------------------------------------------------- \n \n"]; 
 
 
WriteString[file,"Implicit None \n"]; 
MakeVariableList[Flatten[{couplings,masses}],",Intent(in)",file];
WriteString[file,"Integer,Intent(in) :: gt1, gt2,gt3,gt4 \n"];
WriteString[file,"Logical, Intent(in) :: OnlySM \n"];
WriteString[file,"Integer :: iprop, i1, i2, i3, i4 \n"];
WriteString[file,"Real(dp) :: MassEx1,MassEx2,MassEx3,MassEx4, MassEx12,MassEx22,MassEx32,MassEx42 \n"];
WriteString[file,"Complex(dp), Intent(out) :: TSOYphillVRR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOYphillVLL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOYphillVRL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOYphillVLR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOYphillTLL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOYphillTLR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOYphillTRL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOYphillTRR \n"]; 
WriteString[file,"Complex(dp) :: vertex1L, vertex1R, vertex2L, vertex2R \n"];
WriteString[file,"Real(dp) ::  MP, MP2, IMP2, IMP, MFin, MFin2, IMFin, IMFin2, Finite  \n"];
WriteString[file,"Real(dp) ::  MS1, MS12, MS2, MS22, MF1, MF12, MF2, MF22, MV1, MV12, MV2, MV22  \n"];
WriteString[file,"Complex(dp) ::  chargefactor  \n"];
WriteString[file,"Complex(dp) ::  coup1L, coup1R, coup2L, coup2R, coup3L, coup3R, coup3, coup4L, coup4R \n\n"];

WriteString[file,"Complex(dp) ::  int1,int2,int3,int4,int5,int6,int7,int8 \n\n"];

WriteString[file,"Iname=Iname+1 \n"];
WriteString[file,"NameOfUnit(Iname)='CalculateTreeSYphill' \n
"];
 
AddCalcSquaredMasses[masses,file]; 
(* Initaliziation *)
WriteString[file,"Finite=1._dp \n"];
WriteString[file,"MassEx1="<>SPhenoMass[ChargedLepton,gt1]<>"  \n"];
WriteString[file,"MassEx12="<>SPhenoMassSq[ChargedLepton,gt1]<>" \n"];
WriteString[file,"MassEx2="<>SPhenoMass[bar[ChargedLepton],gt2]<>"  \n"];
WriteString[file,"MassEx22="<>SPhenoMassSq[bar[ChargedLepton],gt2]<>" \n"];
WriteString[file,"MassEx3="<>SPhenoMass[DownQuark,gt3]<>"  \n"];
WriteString[file,"MassEx32="<>SPhenoMassSq[DownQuark,gt3]<>" \n"];
WriteString[file,"MassEx4="<>SPhenoMass[bar[DownQuark],gt4]<>"  \n"];
WriteString[file,"MassEx42="<>SPhenoMassSq[bar[DownQuark],gt4]<>" \n"];
WriteString[file,"! ------------------------------ \n "];
WriteString[file,"! Amplitudes for external states \n "];
WriteString[file,"! {ChargedLepton, bar[ChargedLepton], DownQuark, bar[DownQuark]} \n "];
WriteString[file,"! ------------------------------ \n \n"];
WriteString[sphenoTeX,"\\section{External states: $"<>TeXOutput[{ChargedLepton[{gt1}], bar[ChargedLepton][{gt2}], DownQuark[{gt3}], bar[DownQuark][{gt4}]}]<>"$} \n"];
WriteString[file,"TSOYphillVRR=0._dp \n"]; 
WriteString[file,"TSOYphillVLL=0._dp \n"]; 
WriteString[file,"TSOYphillVRL=0._dp \n"]; 
WriteString[file,"TSOYphillVLR=0._dp \n"]; 
WriteString[file,"TSOYphillTLL=0._dp \n"]; 
WriteString[file,"TSOYphillTLR=0._dp \n"]; 
WriteString[file,"TSOYphillTRL=0._dp \n"]; 
WriteString[file,"TSOYphillTRR=0._dp \n"]; 
WriteDiagramsObservable[TreeSYphill,treeScalar, {}, {},  {}, {}, {}, {}, file];
WriteString[file,"Iname=Iname-1\n\n"]; 
WriteString[file,"End Subroutine CalculateTreeSYphill \n\n"]; 
]; 
AddTreeResultPreSARAH[TreeSYphill][prop_,top_,type_,file_]:=Block[{}, 

 (* This routine returns the generic expression for the amplitude of a given triangle diagram *) 
 
Switch[prop,
V, (* Vector penguins *) 
Return[]; (* not necessary *) ,
S, (* Scalar penguins *) 
 Switch[top,  (* Check topology *) 
  1, 
	 	 WriteStringFLB[file,"  TSOYphillVRR=TSOYphillVRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillVRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillVLL=TSOYphillVLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillVLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillVRL=TSOYphillVRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillVRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillVLR=TSOYphillVLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillVLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillTLL=TSOYphillTLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillTLR=TSOYphillTLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillTRL=TSOYphillTRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillTRR=TSOYphillTRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
,
  2, 
	 	 WriteStringFLB[file,"  TSOYphillVRR=TSOYphillVRR+ 0.5*coup1R*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillVRR= & "<> StringReplace["(coup1R coup2L IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillVLL=TSOYphillVLL+ 0.5*coup1L*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillVLL= & "<> StringReplace["(coup1L coup2R IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillVRL=TSOYphillVRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillVRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillVLR=TSOYphillVLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillVLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillTLL=TSOYphillTLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillTLR=TSOYphillTLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillTRL=TSOYphillTRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillTRR=TSOYphillTRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
,
  3, 
	 	 WriteStringFLB[file,"  TSOYphillVRR=TSOYphillVRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillVRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillVLL=TSOYphillVLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillVLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillVRL=TSOYphillVRL+ -0.5*coup1R*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillVRL= & "<> StringReplace["-(coup1R coup2L IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillVLR=TSOYphillVLR+ -0.5*coup1L*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillVLR= & "<> StringReplace["-(coup1L coup2R IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillTLL=TSOYphillTLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillTLR=TSOYphillTLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillTRL=TSOYphillTRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOYphillTRR=TSOYphillTRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOYphillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
];]; 
]; 


