(* Code automatically generated by 'PreSARAH' *) 
(* Expressions for amplitudes are obtained by FeynArts/FormCalc *) 
(* This file is supposed to be loaded and used by SARAH *) 
(* Created at 1:59 on 6.1.2021 *) 
 
 
PrintDebug["   ... ",BoxPsill]; 
NamesParticles =  {ChargedLepton, bar[ChargedLepton], UpQuark, bar[UpQuark]}; 
 NamesOperators =  {BOPsillVRR, BOPsillVLL, BOPsillVRL, BOPsillVLR, BOPsillTLL, BOPsillTLR, BOPsillTRL, BOPsillTRR}; 
 NeglectInsertionOrderBox[BoxPsill] = {}; 
NeglectCrossedDiagrams[BoxPsill] = False; 
NameProcess = BoxPsill; 
 
Generate[BoxPsill][file_]:=Block[{i,j,k}, 
 

 (* Creating all possible processes; extract information about involved masses/couplings *) 


(* ------------------------------- *)
(* {ChargedLepton, bar[ChargedLepton], UpQuark, bar[UpQuark]} *)
(* ------------------------------- *)
 
GetInformtion4FermionProcess[ChargedLepton,bar[ChargedLepton],UpQuark,bar[UpQuark],BoxPsill,file]; 
NeededMassesAll=Intersection[NeededMasses];
NeededCouplingsAll=Intersection[NeededCouplings];
WriteCodeObservablePreSARAH[BoxPsill][NeededMassesAll,NeededCouplingsAll,TreeContributionsScalar,TreeContributionsVector,WaveContributionsScalar,WaveContributionsVector,WaveContributionsPhoton,PenguinContributionsScalar,PenguinContributionsVector,PenguinContributionsPhoton,BoxContributions,file]; 
NeededMassAllSaved[BoxPsill] = masses 
]; 

WriteCodeObservablePreSARAH[BoxPsill][masses_,couplings_,treeScalar_,treeVector_,waveScalar_,waveVector_,wavePhoton_,penguinScalar_,penguinVector_,penguinPhoton_,box_,file_] :=Block[{i,j,k,fermions,scalars}, 
 
NeededMassesAllSaved[BoxPsill] = masses; 
NeededCouplingsAllSaved[BoxPsill] = couplings; 
NeededCombinations[BoxPsill] = {{2, 1, 2, 2}, {3, 1, 2, 2}, {3, 2, 2, 2}}; 
PrintDebug["     writing SPheno code for ",BoxPsill]; 
MakeSubroutineTitle["CalculateBoxPsill",Flatten[{masses,couplings}],{"gt1","gt2","gt3","gt4","OnlySM"}, 
{"BOPsillVRR", "BOPsillVLL", "BOPsillVRL", "BOPsillVLR", "BOPsillTLL", "BOPsillTLR", "BOPsillTRL", "BOPsillTRR"},file]; 
WriteString[file,"! ---------------------------------------------------------------- \n"]; 
WriteString[file,"! Code based on automatically generated SARAH extensions by 'PreSARAH' \n"]; 
WriteString[file,"! Expressions for amplitudes are obtained by FeynArts/FormCalc \n"]; 
WriteString[file,"! Based on user input for process BoxPsill \n"]; 
WriteString[file,"! 'PreSARAH' output has been generated  at 1:59 on 6.1.2021 \n"]; 
WriteString[file,"! ---------------------------------------------------------------- \n \n"]; 
 
 
WriteString[file,"Implicit None \n"]; 
MakeVariableList[Flatten[{couplings,masses}],",Intent(in)",file];
WriteString[file,"Integer,Intent(in) :: gt1, gt2,gt3,gt4 \n"];
WriteString[file,"Logical, Intent(in) :: OnlySM \n"];
WriteString[file,"Integer :: iprop, i1, i2, i3, i4 \n"];
WriteString[file,"Real(dp) :: MassEx1,MassEx2,MassEx3,MassEx4, MassEx12,MassEx22,MassEx32,MassEx42 \n"];
WriteString[file,"Complex(dp), Intent(out) :: BOPsillVRR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: BOPsillVLL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: BOPsillVRL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: BOPsillVLR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: BOPsillTLL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: BOPsillTLR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: BOPsillTRL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: BOPsillTRR \n"]; 
WriteString[file,"Complex(dp) :: vertex1L, vertex1R, vertex2L, vertex2R \n"];
WriteString[file,"Real(dp) ::  MP, MP2, IMP2, IMP, MFin, MFin2, IMFin, IMFin2, Finite  \n"];
WriteString[file,"Real(dp) ::  MS1, MS12, MS2, MS22, MF1, MF12, MF2, MF22, MV1, MV12, MV2, MV22  \n"];
WriteString[file,"Complex(dp) ::  chargefactor  \n"];
WriteString[file,"Complex(dp) ::  coup1L, coup1R, coup2L, coup2R, coup3L, coup3R, coup3, coup4L, coup4R \n\n"];

WriteString[file,"Complex(dp) ::  int1,int2,int3,int4,int5,int6,int7,int8 \n\n"];

WriteString[file,"Iname=Iname+1 \n"];
WriteString[file,"NameOfUnit(Iname)='CalculateBoxPsill' \n
"];
 
AddCalcSquaredMasses[masses,file]; 
(* Initaliziation *)
WriteString[file,"Finite=1._dp \n"];
WriteString[file,"MassEx1="<>SPhenoMass[ChargedLepton,gt1]<>"  \n"];
WriteString[file,"MassEx12="<>SPhenoMassSq[ChargedLepton,gt1]<>" \n"];
WriteString[file,"MassEx2="<>SPhenoMass[bar[ChargedLepton],gt2]<>"  \n"];
WriteString[file,"MassEx22="<>SPhenoMassSq[bar[ChargedLepton],gt2]<>" \n"];
WriteString[file,"MassEx3="<>SPhenoMass[UpQuark,gt3]<>"  \n"];
WriteString[file,"MassEx32="<>SPhenoMassSq[UpQuark,gt3]<>" \n"];
WriteString[file,"MassEx4="<>SPhenoMass[bar[UpQuark],gt4]<>"  \n"];
WriteString[file,"MassEx42="<>SPhenoMassSq[bar[UpQuark],gt4]<>" \n"];
WriteString[file,"! ------------------------------ \n "];
WriteString[file,"! Amplitudes for external states \n "];
WriteString[file,"! {ChargedLepton, bar[ChargedLepton], UpQuark, bar[UpQuark]} \n "];
WriteString[file,"! ------------------------------ \n \n"];
WriteString[sphenoTeX,"\\section{External states: $"<>TeXOutput[{ChargedLepton[{gt1}], bar[ChargedLepton][{gt2}], UpQuark[{gt3}], bar[UpQuark][{gt4}]}]<>"$} \n"];
WriteString[file,"BOPsillVRR=0._dp \n"]; 
WriteString[file,"BOPsillVLL=0._dp \n"]; 
WriteString[file,"BOPsillVRL=0._dp \n"]; 
WriteString[file,"BOPsillVLR=0._dp \n"]; 
WriteString[file,"BOPsillTLL=0._dp \n"]; 
WriteString[file,"BOPsillTLR=0._dp \n"]; 
WriteString[file,"BOPsillTRL=0._dp \n"]; 
WriteString[file,"BOPsillTRR=0._dp \n"]; 
WriteDiagramsObservable[BoxPsill,{}, {}, {}, {}, {}, {}, box, file];
WriteString[file,"BOPsillVRR=oo16pi2*BOPsillVRR \n"]; 
WriteString[file,"BOPsillVLL=oo16pi2*BOPsillVLL \n"]; 
WriteString[file,"BOPsillVRL=oo16pi2*BOPsillVRL \n"]; 
WriteString[file,"BOPsillVLR=oo16pi2*BOPsillVLR \n"]; 
WriteString[file,"BOPsillTLL=oo16pi2*BOPsillTLL \n"]; 
WriteString[file,"BOPsillTLR=oo16pi2*BOPsillTLR \n"]; 
WriteString[file,"BOPsillTRL=oo16pi2*BOPsillTRL \n"]; 
WriteString[file,"BOPsillTRR=oo16pi2*BOPsillTRR \n"]; 
WriteString[file,"Iname=Iname-1\n\n"]; 
WriteString[file,"End Subroutine CalculateBoxPsill \n\n"]; 
]; 
AddBoxResultPreSARAH[BoxPsill][top_,type_,file_]:=Block[{}, 

 (* This routine returns the generic expression for the amplitude of a given box diagram *) 
 
Switch[top, (* check in which order the external legs are glued to the box *) 
1, 
   Switch[type, (* Check the generic type of the diagram *) 
	FSSF, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mS22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mS22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+-1.*chargefactor*coup1R*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["-(chargefactor coup1R coup2L coup3R coup4L I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+-1.*chargefactor*coup1L*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["-(chargefactor coup1L coup2R coup3L coup4R I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+-1.*chargefactor*coup1R*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["-(chargefactor coup1R coup2L coup3L coup4R I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+-1.*chargefactor*coup1L*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["-(chargefactor coup1L coup2R coup3R coup4L I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	SFFS, 
	 	 WriteString[file,"  int1=D00check(mF22, mF12, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF22, mF12, mS12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF22, mF12, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mS12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+-1.*chargefactor*coup1R*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["-(chargefactor coup1R coup2L coup3R coup4L I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+-1.*chargefactor*coup1L*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["-(chargefactor coup1L coup2R coup3L coup4R I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+0.5*chargefactor*coup1R*coup2L*coup3L*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["(chargefactor coup1R coup2L coup3L coup4R I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+0.5*chargefactor*coup1L*coup2R*coup3R*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["(chargefactor coup1L coup2R coup3R coup4L I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	FSVF, 
	 	 WriteString[file,"  int1=MMD0(mF1, mF2, mF12, mF22, mV22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mV22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+chargefactor*coup1R*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["chargefactor coup1R coup2R coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+chargefactor*coup1L*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["chargefactor coup1L coup2L coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+chargefactor*coup1R*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["chargefactor coup1R coup2R coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+chargefactor*coup1L*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["chargefactor coup1L coup2L coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	FVSF, 
	 	 WriteString[file,"  int1=MMD0(mF1, mF2, mF12, mF22, mS22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mS22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+chargefactor*coup1R*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+chargefactor*coup1L*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+chargefactor*coup1R*coup2L*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["chargefactor coup1R coup2L coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+chargefactor*coup1L*coup2R*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["chargefactor coup1L coup2R coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	SFFV, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mF12, mV22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mF12, mV22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=D00check(mF22, mF12, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["D_{27}(mF22, mF12, mS12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int3=MMD0(mF1, mF2, mF22, mF12, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_3 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mS12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+chargefactor*coup1R*coup2L*coup3R*coup4R*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4R I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+chargefactor*coup1L*coup2R*coup3L*coup4L*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4L I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+-1.*chargefactor*coup1R*coup2L*coup3L*coup4L*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["-(chargefactor coup1R coup2L coup3L coup4L (I_1 - 2 I_2))",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+-1.*chargefactor*coup1L*coup2R*coup3R*coup4R*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["-(chargefactor coup1L coup2R coup3R coup4R (I_1 - 2 I_2))",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	VFFS, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mF12, mS22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mF12, mS22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=D00check(mF22, mF12, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["D_{27}(mF22, mF12, mV12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int3=MMD0(mF1, mF2, mF22, mF12, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_3 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mV12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+chargefactor*coup1R*coup2R*coup3R*coup4L*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["chargefactor coup1R coup2R coup3R coup4L I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+chargefactor*coup1L*coup2L*coup3L*coup4R*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["chargefactor coup1L coup2L coup3L coup4R I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+-1.*chargefactor*coup1R*coup2R*coup3L*coup4R*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["-(chargefactor coup1R coup2R coup3L coup4R (I_1 - 2 I_2))",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+-1.*chargefactor*coup1L*coup2L*coup3R*coup4L*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["-(chargefactor coup1L coup2L coup3R coup4L (I_1 - 2 I_2))",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	FVVF, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mV22, mV12, mF12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mV22, mV12, mF12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=D00check(mF12, mF22, mV22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["D_{27}(mF12, mF22, mV22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+-4.*chargefactor*coup1R*coup2R*coup3R*coup4R*(int1 - 3.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["-4 chargefactor coup1R coup2R coup3R coup4R (I_1 - 3 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+-4.*chargefactor*coup1L*coup2L*coup3L*coup4L*(int1 - 3.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["-4 chargefactor coup1L coup2L coup3L coup4L (I_1 - 3 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+-4.*chargefactor*coup1R*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["-4 chargefactor coup1R coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+-4.*chargefactor*coup1L*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["-4 chargefactor coup1L coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	VFFV, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mF12, mV22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mF12, mV22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=D00check(mF22, mF12, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["D_{27}(mF22, mF12, mV12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int3=MMD0(mF1, mF2, mF22, mF12, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_3 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mV12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+-4.*chargefactor*coup1R*coup2R*coup3R*coup4R*(int1 - 3.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["-4 chargefactor coup1R coup2R coup3R coup4R (I_1 - 3 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+-4.*chargefactor*coup1L*coup2L*coup3L*coup4L*(int1 - 3.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["-4 chargefactor coup1L coup2L coup3L coup4L (I_1 - 3 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+2.*chargefactor*coup1R*coup2R*coup3L*coup4L*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["2 chargefactor coup1R coup2R coup3L coup4L I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+2.*chargefactor*coup1L*coup2L*coup3R*coup4R*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["2 chargefactor coup1L coup2L coup3R coup4R I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
];,
2, 
   Switch[type, (* Check the generic type of the diagram *) 
	FSSF, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mS22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mS22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+chargefactor*coup1R*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+chargefactor*coup1L*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+chargefactor*coup1R*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+chargefactor*coup1L*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	SFFS, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mS12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF12, mF22, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mS12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+-0.5*chargefactor*coup1R*coup2L*coup3L*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["-(chargefactor coup1R coup2L coup3L coup4R I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+-0.5*chargefactor*coup1L*coup2R*coup3R*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["-(chargefactor coup1L coup2R coup3R coup4L I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+chargefactor*coup1R*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+chargefactor*coup1L*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	FSVF, 
	 	 WriteString[file,"  int1=MMD0(mF1, mF2, mF12, mF22, mV22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mV22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+chargefactor*coup1R*coup2R*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["chargefactor coup1R coup2R coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+chargefactor*coup1L*coup2L*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["chargefactor coup1L coup2L coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+chargefactor*coup1R*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["chargefactor coup1R coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+chargefactor*coup1L*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["chargefactor coup1L coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	FVSF, 
	 	 WriteString[file,"  int1=MMD0(mF1, mF2, mF12, mF22, mS22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mS22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+chargefactor*coup1R*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+chargefactor*coup1L*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+chargefactor*coup1R*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+chargefactor*coup1L*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	SFFV, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mS12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF12, mF22, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mS12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+2.*chargefactor*coup1R*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["2 chargefactor coup1R coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+2.*chargefactor*coup1L*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["2 chargefactor coup1L coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+-1.*chargefactor*coup1R*coup2L*coup3L*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["-(chargefactor coup1R coup2L coup3L coup4L I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+-1.*chargefactor*coup1L*coup2R*coup3R*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["-(chargefactor coup1L coup2R coup3R coup4R I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	VFFS, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mV12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF12, mF22, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mV12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+2.*chargefactor*coup1R*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["2 chargefactor coup1R coup2R coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+2.*chargefactor*coup1L*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["2 chargefactor coup1L coup2L coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+-1.*chargefactor*coup1R*coup2R*coup3R*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["-(chargefactor coup1R coup2R coup3R coup4L I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+-1.*chargefactor*coup1L*coup2L*coup3L*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["-(chargefactor coup1L coup2L coup3L coup4R I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	FVVF, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mV22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mV22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+16.*chargefactor*coup1R*coup2R*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["16 chargefactor coup1R coup2R coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+16.*chargefactor*coup1L*coup2L*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["16 chargefactor coup1L coup2L coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+4.*chargefactor*coup1R*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["4 chargefactor coup1R coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+4.*chargefactor*coup1L*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["4 chargefactor coup1L coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	VFFV, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mV12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF12, mF22, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mV12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+-2.*chargefactor*coup1R*coup2R*coup3R*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["-2 chargefactor coup1R coup2R coup3R coup4R I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+-2.*chargefactor*coup1L*coup2L*coup3L*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["-2 chargefactor coup1L coup2L coup3L coup4L I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+4.*chargefactor*coup1R*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["4 chargefactor coup1R coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+4.*chargefactor*coup1L*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["4 chargefactor coup1L coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
];,
3, 
   Switch[type, (* Check the generic type of the diagram *) 
	FSSF, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mS22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mS22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF12, mF22, mS22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mS22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+-0.5*chargefactor*coup1R*coup2L*coup3R*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["-(chargefactor coup1R coup2L coup3R coup4L I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+-0.5*chargefactor*coup1L*coup2R*coup3L*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["-(chargefactor coup1L coup2R coup3L coup4R I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+-1.*chargefactor*coup1R*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["-(chargefactor coup1R coup2R coup3L coup4L I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+-1.*chargefactor*coup1L*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["-(chargefactor coup1L coup2L coup3R coup4R I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	SFFS, 
	 	 WriteString[file,"  int1=D00check(mF22, mF12, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF22, mF12, mS12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF22, mF12, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mS12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+chargefactor*coup1R*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+chargefactor*coup1L*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+0.5*chargefactor*coup1R*coup2R*coup3L*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["(chargefactor coup1R coup2R coup3L coup4L I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+0.5*chargefactor*coup1L*coup2L*coup3R*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["(chargefactor coup1L coup2L coup3R coup4R I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	FSVF, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mV22, mS12, mF12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mV22, mS12, mF12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=D00check(mF12, mF22, mV22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["D_{27}(mF12, mF22, mV22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int3=MMD0(mF1, mF2, mF12, mF22, mV22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_3 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mV22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+chargefactor*coup1R*coup2L*coup3R*coup4R*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4R (I_1 - 2 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+chargefactor*coup1L*coup2R*coup3L*coup4L*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4L (I_1 - 2 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+chargefactor*coup1R*coup2R*coup3L*coup4R*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["chargefactor coup1R coup2R coup3L coup4R I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+chargefactor*coup1L*coup2L*coup3R*coup4L*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["chargefactor coup1L coup2L coup3R coup4L I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	FVSF, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mS22, mV12, mF12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mS22, mV12, mF12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=D00check(mF12, mF22, mS22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["D_{27}(mF12, mF22, mS22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int3=MMD0(mF1, mF2, mF12, mF22, mS22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_3 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mS22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+chargefactor*coup1R*coup2R*coup3R*coup4L*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["chargefactor coup1R coup2R coup3R coup4L (I_1 - 2 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+chargefactor*coup1L*coup2L*coup3L*coup4R*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["chargefactor coup1L coup2L coup3L coup4R (I_1 - 2 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+chargefactor*coup1R*coup2L*coup3L*coup4L*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["chargefactor coup1R coup2L coup3L coup4L I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+chargefactor*coup1L*coup2R*coup3R*coup4R*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["chargefactor coup1L coup2R coup3R coup4R I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	SFFV, 
	 	 WriteString[file,"  int1=D00check(mF22, mF12, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF22, mF12, mS12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF22, mF12, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mS12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+chargefactor*coup1R*coup2R*coup3R*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["chargefactor coup1R coup2R coup3R coup4R I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+chargefactor*coup1L*coup2L*coup3L*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["chargefactor coup1L coup2L coup3L coup4L I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+2.*chargefactor*coup1R*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["2 chargefactor coup1R coup2L coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+2.*chargefactor*coup1L*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["2 chargefactor coup1L coup2R coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	VFFS, 
	 	 WriteString[file,"  int1=D00check(mF22, mF12, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF22, mF12, mV12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF22, mF12, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mV12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+chargefactor*coup1R*coup2L*coup3R*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4L I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+chargefactor*coup1L*coup2R*coup3L*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4R I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+2.*chargefactor*coup1R*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["2 chargefactor coup1R coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+2.*chargefactor*coup1L*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["2 chargefactor coup1L coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	FVVF, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mV22, mV12, mF12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mV22, mV12, mF12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF12, mF22, mV22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mV22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+-2.*chargefactor*coup1R*coup2R*coup3R*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["-2 chargefactor coup1R coup2R coup3R coup4R I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+-2.*chargefactor*coup1L*coup2L*coup3L*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["-2 chargefactor coup1L coup2L coup3L coup4L I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+-4.*chargefactor*coup1R*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["-4 chargefactor coup1R coup2L coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+-4.*chargefactor*coup1L*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["-4 chargefactor coup1L coup2R coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
,
	VFFV, 
	 	 WriteString[file,"  int1=D00check(mF22, mF12, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF22, mF12, mV12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF22, mF12, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mV12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOPsillVRR=BOPsillVRR+16.*chargefactor*coup1R*coup2R*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRR= & "<> StringReplace["16 chargefactor coup1R coup2R coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLL=BOPsillVLL+16.*chargefactor*coup1L*coup2L*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLL= & "<> StringReplace["16 chargefactor coup1L coup2L coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVRL=BOPsillVRL+2.*chargefactor*coup1R*coup2L*coup3L*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVRL= & "<> StringReplace["2 chargefactor coup1R coup2L coup3L coup4R I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillVLR=BOPsillVLR+2.*chargefactor*coup1L*coup2R*coup3R*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillVLR= & "<> StringReplace["2 chargefactor coup1L coup2R coup3R coup4L I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLL=BOPsillTLL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTLR=BOPsillTLR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRL=BOPsillTRL+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  BOPsillTRR=BOPsillTRR+0.\n" ];
	 	 WriteString[sphenoTeX,"  BOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub] <>" \\\\ \n" ];
];]; 
]; 


