(* Code automatically generated by 'PreSARAH' *) 
(* Expressions for amplitudes are obtained by FeynArts/FormCalc *) 
(* This file is supposed to be loaded and used by SARAH *) 
(* Created at 2:01 on 6.1.2021 *) 
 
 
PrintDebug["   ... ",TreeVPsill]; 
NamesParticles =  {ChargedLepton, bar[ChargedLepton], UpQuark, bar[UpQuark]}; 
 NamesOperators =  {TVOPsillVRR, TVOPsillVLL, TVOPsillVRL, TVOPsillVLR, TVOPsillTLL, TVOPsillTLR, TVOPsillTRL, TVOPsillTRR}; 
 NeglectInsertionOrderTree[TreeVPsill] =  {}; 
NeglectCrossedDiagrams[TreeVPsill] = False; 
NameProcess = TreeVPsill; 
 
Generate[TreeVPsill][file_]:=Block[{i,j,k}, 
 

 (* Creating all possible processes; extract information about involved masses/couplings *) 


(* ------------------------------- *)
(* {ChargedLepton, bar[ChargedLepton], UpQuark, bar[UpQuark]} *)
(* ------------------------------- *)
 
GetInformtion4FermionProcess[ChargedLepton,bar[ChargedLepton],UpQuark,bar[UpQuark],TreeVPsill,file]; 
NeededMassesAll=Intersection[NeededMasses];
NeededCouplingsAll=Intersection[NeededCouplings];
WriteCodeObservablePreSARAH[TreeVPsill][NeededMassesAll,NeededCouplingsAll,TreeContributionsScalar,TreeContributionsVector,WaveContributionsScalar,WaveContributionsVector,WaveContributionsPhoton,PenguinContributionsScalar,PenguinContributionsVector,PenguinContributionsPhoton,BoxContributions,file]; 
NeededMassAllSaved[TreeVPsill] = masses 
]; 

WriteCodeObservablePreSARAH[TreeVPsill][masses_,couplings_,treeScalar_,treeVector_,waveScalar_,waveVector_,wavePhoton_,penguinScalar_,penguinVector_,penguinPhoton_,box_,file_] :=Block[{i,j,k,fermions,scalars}, 
 
NeededMassesAllSaved[TreeVPsill] = masses; 
NeededCouplingsAllSaved[TreeVPsill] = couplings; 
NeededCombinations[TreeVPsill] = {{2, 1, 2, 2}, {3, 1, 2, 2}, {3, 2, 2, 2}}; 
PrintDebug["     writing SPheno code for ",TreeVPsill]; 
MakeSubroutineTitle["CalculateTreeVPsill",Flatten[{masses,couplings}],{"gt1","gt2","gt3","gt4","OnlySM"}, 
{"TVOPsillVRR", "TVOPsillVLL", "TVOPsillVRL", "TVOPsillVLR", "TVOPsillTLL", "TVOPsillTLR", "TVOPsillTRL", "TVOPsillTRR"},file]; 
WriteString[file,"! ---------------------------------------------------------------- \n"]; 
WriteString[file,"! Code based on automatically generated SARAH extensions by 'PreSARAH' \n"]; 
WriteString[file,"! Expressions for amplitudes are obtained by FeynArts/FormCalc \n"]; 
WriteString[file,"! Based on user input for process TreeVPsill \n"]; 
WriteString[file,"! 'PreSARAH' output has been generated  at 2:01 on 6.1.2021 \n"]; 
WriteString[file,"! ---------------------------------------------------------------- \n \n"]; 
 
 
WriteString[file,"Implicit None \n"]; 
MakeVariableList[Flatten[{couplings,masses}],",Intent(in)",file];
WriteString[file,"Integer,Intent(in) :: gt1, gt2,gt3,gt4 \n"];
WriteString[file,"Logical, Intent(in) :: OnlySM \n"];
WriteString[file,"Integer :: iprop, i1, i2, i3, i4 \n"];
WriteString[file,"Real(dp) :: MassEx1,MassEx2,MassEx3,MassEx4, MassEx12,MassEx22,MassEx32,MassEx42 \n"];
WriteString[file,"Complex(dp), Intent(out) :: TVOPsillVRR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVOPsillVLL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVOPsillVRL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVOPsillVLR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVOPsillTLL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVOPsillTLR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVOPsillTRL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVOPsillTRR \n"]; 
WriteString[file,"Complex(dp) :: vertex1L, vertex1R, vertex2L, vertex2R \n"];
WriteString[file,"Real(dp) ::  MP, MP2, IMP2, IMP, MFin, MFin2, IMFin, IMFin2, Finite  \n"];
WriteString[file,"Real(dp) ::  MS1, MS12, MS2, MS22, MF1, MF12, MF2, MF22, MV1, MV12, MV2, MV22  \n"];
WriteString[file,"Complex(dp) ::  chargefactor  \n"];
WriteString[file,"Complex(dp) ::  coup1L, coup1R, coup2L, coup2R, coup3L, coup3R, coup3, coup4L, coup4R \n\n"];

WriteString[file,"Complex(dp) ::  int1,int2,int3,int4,int5,int6,int7,int8 \n\n"];

WriteString[file,"Iname=Iname+1 \n"];
WriteString[file,"NameOfUnit(Iname)='CalculateTreeVPsill' \n
"];
 
AddCalcSquaredMasses[masses,file]; 
(* Initaliziation *)
WriteString[file,"Finite=1._dp \n"];
WriteString[file,"MassEx1="<>SPhenoMass[ChargedLepton,gt1]<>"  \n"];
WriteString[file,"MassEx12="<>SPhenoMassSq[ChargedLepton,gt1]<>" \n"];
WriteString[file,"MassEx2="<>SPhenoMass[bar[ChargedLepton],gt2]<>"  \n"];
WriteString[file,"MassEx22="<>SPhenoMassSq[bar[ChargedLepton],gt2]<>" \n"];
WriteString[file,"MassEx3="<>SPhenoMass[UpQuark,gt3]<>"  \n"];
WriteString[file,"MassEx32="<>SPhenoMassSq[UpQuark,gt3]<>" \n"];
WriteString[file,"MassEx4="<>SPhenoMass[bar[UpQuark],gt4]<>"  \n"];
WriteString[file,"MassEx42="<>SPhenoMassSq[bar[UpQuark],gt4]<>" \n"];
WriteString[file,"! ------------------------------ \n "];
WriteString[file,"! Amplitudes for external states \n "];
WriteString[file,"! {ChargedLepton, bar[ChargedLepton], UpQuark, bar[UpQuark]} \n "];
WriteString[file,"! ------------------------------ \n \n"];
WriteString[sphenoTeX,"\\section{External states: $"<>TeXOutput[{ChargedLepton[{gt1}], bar[ChargedLepton][{gt2}], UpQuark[{gt3}], bar[UpQuark][{gt4}]}]<>"$} \n"];
WriteString[file,"TVOPsillVRR=0._dp \n"]; 
WriteString[file,"TVOPsillVLL=0._dp \n"]; 
WriteString[file,"TVOPsillVRL=0._dp \n"]; 
WriteString[file,"TVOPsillVLR=0._dp \n"]; 
WriteString[file,"TVOPsillTLL=0._dp \n"]; 
WriteString[file,"TVOPsillTLR=0._dp \n"]; 
WriteString[file,"TVOPsillTRL=0._dp \n"]; 
WriteString[file,"TVOPsillTRR=0._dp \n"]; 
WriteDiagramsObservable[TreeVPsill,{}, treeVector, {},  {}, {}, {}, {}, file];
WriteString[file,"Iname=Iname-1\n\n"]; 
WriteString[file,"End Subroutine CalculateTreeVPsill \n\n"]; 
]; 
AddTreeResultPreSARAH[TreeVPsill][prop_,top_,type_,file_]:=Block[{}, 

 (* This routine returns the generic expression for the amplitude of a given triangle diagram *) 
 
Switch[prop,
V, (* Vector penguins *) 
 Switch[top,  (* Check topology *) 
  1, 
	 	 WriteStringFLB[file,"  TVOPsillVRR=TVOPsillVRR+ -1.*coup1R*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillVRR= & "<> StringReplace["-(coup1R coup2R IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillVLL=TVOPsillVLL+ -1.*coup1L*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillVLL= & "<> StringReplace["-(coup1L coup2L IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillVRL=TVOPsillVRL+ -1.*coup1R*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillVRL= & "<> StringReplace["-(coup1R coup2L IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillVLR=TVOPsillVLR+ -1.*coup1L*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillVLR= & "<> StringReplace["-(coup1L coup2R IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillTLL=TVOPsillTLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillTLR=TVOPsillTLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillTRL=TVOPsillTRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillTRR=TVOPsillTRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
,
  2, 
	 	 WriteStringFLB[file,"  TVOPsillVRR=TVOPsillVRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillVRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillVLL=TVOPsillVLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillVLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillVRL=TVOPsillVRL+ -1.*coup1L*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillVRL= & "<> StringReplace["-(coup1L coup2R IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillVLR=TVOPsillVLR+ -1.*coup1R*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillVLR= & "<> StringReplace["-(coup1R coup2L IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillTLL=TVOPsillTLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillTLR=TVOPsillTLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillTRL=TVOPsillTRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillTRR=TVOPsillTRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
,
  3, 
	 	 WriteStringFLB[file,"  TVOPsillVRR=TVOPsillVRR+ -1.*coup1R*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillVRR= & "<> StringReplace["-(coup1R coup2R IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillVLL=TVOPsillVLL+ -1.*coup1L*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillVLL= & "<> StringReplace["-(coup1L coup2L IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillVRL=TVOPsillVRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillVRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillVLR=TVOPsillVLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillVLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillTLL=TVOPsillTLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillTLR=TVOPsillTLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillTRL=TVOPsillTRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TVOPsillTRR=TVOPsillTRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
];,
S, (* Scalar penguins *) 
Return[]; (* not necessary *) ]; 
]; 


