(* Code automatically generated by 'PreSARAH' *) 
(* Created at 1:58 on 6.1.2021 *) 
 
 
ProcessWrapper = True; 
NameProcess = "Psill" 
ExternalFields = {ChargedLepton, bar[ChargedLepton], UpQuark, bar[UpQuark]}; 
SumContributionsOperators["Psill"] = { 
{OPsillVRR, BOPsillVRR + PSOPsillVRR + PVOPsillVRR + TSOPsillVRR + TVOPsillVRR}, 
{OPsillVLL, BOPsillVLL + PSOPsillVLL + PVOPsillVLL + TSOPsillVLL + TVOPsillVLL}, 
{OPsillVRL, BOPsillVRL + PSOPsillVRL + PVOPsillVRL + TSOPsillVRL + TVOPsillVRL}, 
{OPsillVLR, BOPsillVLR + PSOPsillVLR + PVOPsillVLR + TSOPsillVLR + TVOPsillVLR}, 
{OPsillTLL, BOPsillTLL + PSOPsillTLL + PVOPsillTLL + TSOPsillTLL + TVOPsillTLL}, 
{OPsillTLR, BOPsillTLR + PSOPsillTLR + PVOPsillTLR + TSOPsillTLR + TVOPsillTLR}, 
{OPsillTRL, BOPsillTRL + PSOPsillTRL + PVOPsillTRL + TSOPsillTRL + TVOPsillTRL}, 
{OPsillTRR, BOPsillTRR + PSOPsillTRR + PVOPsillTRR + TSOPsillTRR + TVOPsillTRR}}; 

