(* Code automatically generated by 'PreSARAH' *) 
(* Expressions for amplitudes are obtained by FeynArts/FormCalc *) 
(* This file is supposed to be loaded and used by SARAH *) 
(* Created at 2:01 on 6.1.2021 *) 
 
 
PrintDebug["   ... ",TreeSPsill]; 
NamesParticles =  {ChargedLepton, bar[ChargedLepton], UpQuark, bar[UpQuark]}; 
 NamesOperators =  {TSOPsillVRR, TSOPsillVLL, TSOPsillVRL, TSOPsillVLR, TSOPsillTLL, TSOPsillTLR, TSOPsillTRL, TSOPsillTRR}; 
 NeglectInsertionOrderTree[TreeSPsill] =  {}; 
NeglectCrossedDiagrams[TreeSPsill] = False; 
NameProcess = TreeSPsill; 
 
Generate[TreeSPsill][file_]:=Block[{i,j,k}, 
 

 (* Creating all possible processes; extract information about involved masses/couplings *) 


(* ------------------------------- *)
(* {ChargedLepton, bar[ChargedLepton], UpQuark, bar[UpQuark]} *)
(* ------------------------------- *)
 
GetInformtion4FermionProcess[ChargedLepton,bar[ChargedLepton],UpQuark,bar[UpQuark],TreeSPsill,file]; 
NeededMassesAll=Intersection[NeededMasses];
NeededCouplingsAll=Intersection[NeededCouplings];
WriteCodeObservablePreSARAH[TreeSPsill][NeededMassesAll,NeededCouplingsAll,TreeContributionsScalar,TreeContributionsVector,WaveContributionsScalar,WaveContributionsVector,WaveContributionsPhoton,PenguinContributionsScalar,PenguinContributionsVector,PenguinContributionsPhoton,BoxContributions,file]; 
NeededMassAllSaved[TreeSPsill] = masses 
]; 

WriteCodeObservablePreSARAH[TreeSPsill][masses_,couplings_,treeScalar_,treeVector_,waveScalar_,waveVector_,wavePhoton_,penguinScalar_,penguinVector_,penguinPhoton_,box_,file_] :=Block[{i,j,k,fermions,scalars}, 
 
NeededMassesAllSaved[TreeSPsill] = masses; 
NeededCouplingsAllSaved[TreeSPsill] = couplings; 
NeededCombinations[TreeSPsill] = {{2, 1, 2, 2}, {3, 1, 2, 2}, {3, 2, 2, 2}}; 
PrintDebug["     writing SPheno code for ",TreeSPsill]; 
MakeSubroutineTitle["CalculateTreeSPsill",Flatten[{masses,couplings}],{"gt1","gt2","gt3","gt4","OnlySM"}, 
{"TSOPsillVRR", "TSOPsillVLL", "TSOPsillVRL", "TSOPsillVLR", "TSOPsillTLL", "TSOPsillTLR", "TSOPsillTRL", "TSOPsillTRR"},file]; 
WriteString[file,"! ---------------------------------------------------------------- \n"]; 
WriteString[file,"! Code based on automatically generated SARAH extensions by 'PreSARAH' \n"]; 
WriteString[file,"! Expressions for amplitudes are obtained by FeynArts/FormCalc \n"]; 
WriteString[file,"! Based on user input for process TreeSPsill \n"]; 
WriteString[file,"! 'PreSARAH' output has been generated  at 2:01 on 6.1.2021 \n"]; 
WriteString[file,"! ---------------------------------------------------------------- \n \n"]; 
 
 
WriteString[file,"Implicit None \n"]; 
MakeVariableList[Flatten[{couplings,masses}],",Intent(in)",file];
WriteString[file,"Integer,Intent(in) :: gt1, gt2,gt3,gt4 \n"];
WriteString[file,"Logical, Intent(in) :: OnlySM \n"];
WriteString[file,"Integer :: iprop, i1, i2, i3, i4 \n"];
WriteString[file,"Real(dp) :: MassEx1,MassEx2,MassEx3,MassEx4, MassEx12,MassEx22,MassEx32,MassEx42 \n"];
WriteString[file,"Complex(dp), Intent(out) :: TSOPsillVRR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOPsillVLL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOPsillVRL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOPsillVLR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOPsillTLL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOPsillTLR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOPsillTRL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOPsillTRR \n"]; 
WriteString[file,"Complex(dp) :: vertex1L, vertex1R, vertex2L, vertex2R \n"];
WriteString[file,"Real(dp) ::  MP, MP2, IMP2, IMP, MFin, MFin2, IMFin, IMFin2, Finite  \n"];
WriteString[file,"Real(dp) ::  MS1, MS12, MS2, MS22, MF1, MF12, MF2, MF22, MV1, MV12, MV2, MV22  \n"];
WriteString[file,"Complex(dp) ::  chargefactor  \n"];
WriteString[file,"Complex(dp) ::  coup1L, coup1R, coup2L, coup2R, coup3L, coup3R, coup3, coup4L, coup4R \n\n"];

WriteString[file,"Complex(dp) ::  int1,int2,int3,int4,int5,int6,int7,int8 \n\n"];

WriteString[file,"Iname=Iname+1 \n"];
WriteString[file,"NameOfUnit(Iname)='CalculateTreeSPsill' \n
"];
 
AddCalcSquaredMasses[masses,file]; 
(* Initaliziation *)
WriteString[file,"Finite=1._dp \n"];
WriteString[file,"MassEx1="<>SPhenoMass[ChargedLepton,gt1]<>"  \n"];
WriteString[file,"MassEx12="<>SPhenoMassSq[ChargedLepton,gt1]<>" \n"];
WriteString[file,"MassEx2="<>SPhenoMass[bar[ChargedLepton],gt2]<>"  \n"];
WriteString[file,"MassEx22="<>SPhenoMassSq[bar[ChargedLepton],gt2]<>" \n"];
WriteString[file,"MassEx3="<>SPhenoMass[UpQuark,gt3]<>"  \n"];
WriteString[file,"MassEx32="<>SPhenoMassSq[UpQuark,gt3]<>" \n"];
WriteString[file,"MassEx4="<>SPhenoMass[bar[UpQuark],gt4]<>"  \n"];
WriteString[file,"MassEx42="<>SPhenoMassSq[bar[UpQuark],gt4]<>" \n"];
WriteString[file,"! ------------------------------ \n "];
WriteString[file,"! Amplitudes for external states \n "];
WriteString[file,"! {ChargedLepton, bar[ChargedLepton], UpQuark, bar[UpQuark]} \n "];
WriteString[file,"! ------------------------------ \n \n"];
WriteString[sphenoTeX,"\\section{External states: $"<>TeXOutput[{ChargedLepton[{gt1}], bar[ChargedLepton][{gt2}], UpQuark[{gt3}], bar[UpQuark][{gt4}]}]<>"$} \n"];
WriteString[file,"TSOPsillVRR=0._dp \n"]; 
WriteString[file,"TSOPsillVLL=0._dp \n"]; 
WriteString[file,"TSOPsillVRL=0._dp \n"]; 
WriteString[file,"TSOPsillVLR=0._dp \n"]; 
WriteString[file,"TSOPsillTLL=0._dp \n"]; 
WriteString[file,"TSOPsillTLR=0._dp \n"]; 
WriteString[file,"TSOPsillTRL=0._dp \n"]; 
WriteString[file,"TSOPsillTRR=0._dp \n"]; 
WriteDiagramsObservable[TreeSPsill,treeScalar, {}, {},  {}, {}, {}, {}, file];
WriteString[file,"Iname=Iname-1\n\n"]; 
WriteString[file,"End Subroutine CalculateTreeSPsill \n\n"]; 
]; 
AddTreeResultPreSARAH[TreeSPsill][prop_,top_,type_,file_]:=Block[{}, 

 (* This routine returns the generic expression for the amplitude of a given triangle diagram *) 
 
Switch[prop,
V, (* Vector penguins *) 
Return[]; (* not necessary *) ,
S, (* Scalar penguins *) 
 Switch[top,  (* Check topology *) 
  1, 
	 	 WriteStringFLB[file,"  TSOPsillVRR=TSOPsillVRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillVRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillVLL=TSOPsillVLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillVLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillVRL=TSOPsillVRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillVRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillVLR=TSOPsillVLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillVLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillTLL=TSOPsillTLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillTLR=TSOPsillTLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillTRL=TSOPsillTRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillTRR=TSOPsillTRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
,
  2, 
	 	 WriteStringFLB[file,"  TSOPsillVRR=TSOPsillVRR+ 0.5*coup1R*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillVRR= & "<> StringReplace["(coup1R coup2L IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillVLL=TSOPsillVLL+ 0.5*coup1L*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillVLL= & "<> StringReplace["(coup1L coup2R IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillVRL=TSOPsillVRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillVRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillVLR=TSOPsillVLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillVLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillTLL=TSOPsillTLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillTLR=TSOPsillTLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillTRL=TSOPsillTRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillTRR=TSOPsillTRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
,
  3, 
	 	 WriteStringFLB[file,"  TSOPsillVRR=TSOPsillVRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillVRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillVLL=TSOPsillVLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillVLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillVRL=TSOPsillVRL+ -0.5*coup1R*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillVRL= & "<> StringReplace["-(coup1R coup2L IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillVLR=TSOPsillVLR+ -0.5*coup1L*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillVLR= & "<> StringReplace["-(coup1L coup2R IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillTLL=TSOPsillTLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillTLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillTLR=TSOPsillTLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillTLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillTRL=TSOPsillTRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillTRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSOPsillTRR=TSOPsillTRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOPsillTRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
];]; 
]; 


